//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgientPriceProperty
{
    using System;
    using System.Collections.Generic;
    
    public partial class specifications
    {
        public int id { get; set; }
        public string title { get; set; }
        public int idViewProperty { get; set; }
    
        public virtual viewProperty viewProperty { get; set; }
    }
}
