//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgientPriceProperty
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeWork
    {
        public int id { get; set; }
        public System.DateTime dateWork { get; set; }
        public System.TimeSpan timeStart { get; set; }
        public System.TimeSpan timeFinish { get; set; }
        public int tabelNumberPerson { get; set; }
        public int money { get; set; }
        public int moreHour { get; set; }

        public virtual Employeer Employeer { get; set; }
    }
}
